FROM ghcr.io/cirruslabs/flutter:3.29.1

WORKDIR /app
COPY pubspec.* ./
RUN flutter pub get

RUN flutter doctor

COPY . .
EXPOSE 8080
CMD ["flutter", "run", "--web-server-bind-address", "0.0.0.0", "--web-port", "8080"]
