
services:
  # Flutter UI
  flutter_ui:
        build:
          context: ./flutter_ui
          dockerfile: Dockerfile.dev
        dns:
          - 8.8.8.8
        ports:
          - "8090:8080"  # Or whatever port Flutter is using
        volumes:
          - ./flutter_ui:/app
          - flutter_modules:/app/node_modules # Persist node_modules
        depends_on:
          - backend_api
        environment:
          - BACKEND_API_URL=http://backend_api:3000  # Points to Go backend

  # Go Backend API
  backend_api:
    build:
      context: ./backend_api
      dockerfile: Dockerfile.dev # Ensure this installs dependencies
    ports:
      - "3000:3000"
    volumes:
      #- ./backend_api:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/database  # Replace
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - db
      - rabbitmq

  # Go Agent
  go_agent:
    build:
      context: ./go_agent
      dockerfile: Dockerfile.dev
    volumes:
      - ./go_agent:/app
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket (SECURITY RISK!)
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - DATABASE_URL=postgresql://user:password@db:5432/database
    depends_on:
      - rabbitmq
      - db

  # Go CLI
  go_cli:
    build:
      context: ./go_cli
      dockerfile: Dockerfile.dev
    volumes:
      - ./go_cli:/app
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/ # Needed if CLI uses RabbitMQ directly.
    depends_on:
      - rabbitmq # Only needed if CLI interacts with RabbitMQ directly.

  # PostgreSQL Database
  db:
    image: postgres:15  # Or your preferred version
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    volumes:
      - db_data:/var/lib/postgresql/data

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3.9-management  # Or your preferred version with management UI
    ports:
      - "5672:5672"
      - "15672:15672"  # Management UI

# Volumes to persist data across container restarts
volumes:
  db_data:
  flutter_modules:   # Keep for Flutter's web dependencies (JS)
