FROM golang:1.23-alpine

WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source code
COPY . .

# Build the application
RUN go build -o /tmp/qa-cli .

# Copy the binary to the /app directory
RUN cp /tmp/qa-cli /app/qa-cli

# Add debugging commands
RUN apk add --no-cache libc6-compat
RUN chmod +x /app/qa-cli
RUN ls -l /app

# Command to run the executable
CMD ["/app/qa-cli"]
